name: build_test.yml
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Building the project..."
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Create build directory"
        run: mkdir -p builds

      - name: "Generate CMake build files"
        run: cmake -S . -B builds

      - name: "Build the project"
        run: cmake --build builds

  tests:
    needs: build
    name: "Run tests on the build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Rebuild the project for tests"
        run: |
          mkdir -p builds
          cmake -S . -B builds
          cmake --build builds

      - name: "Run tests"
        run: ./src/Tests/YacTests
        working-directory: builds
